local map = vim.keymap.set

map("n", "<leader>dpr", function()
	require("dap-python").test_method()
end, { desc = "Run Python test method" })

map("n", "<F5>", function()
	require("dap").continue()
end, { desc = "Debug: continue/start" })
map("n", "<F10>", function()
	require("dap").step_over()
end, { desc = "Debug: step over" })
map("n", "<F11>", function()
	require("dap").step_into()
end, { desc = "Debug: step into" })
map("n", "<F12>", function()
	require("dap").step_out()
end, { desc = "Debug: step out" })
map("n", "<Leader>b", function()
	require("dap").toggle_breakpoint()
end, { desc = "Debug: toggle breakpoint" })
map("n", "<Leader>B", function()
	require("dap").set_breakpoint()
end, { desc = "Debug: set breakpoint" })
map("n", "<Leader>lp", function()
	require("dap").set_breakpoint(nil, nil, vim.fn.input("Log point message: "))
end, { desc = "Debug: set log point" })
map("n", "<Leader>dr", function()
	require("dap").repl.open()
end, { desc = "Debug: open REPL" })
map("n", "<Leader>dl", function()
	require("dap").run_last()
end, { desc = "Debug: run last" })
map({ "n", "v" }, "<Leader>dh", function()
	require("dap.ui.widgets").hover()
end, { desc = "Debug: hover widget" })
map({ "n", "v" }, "<Leader>dp", function()
	require("dap.ui.widgets").preview()
end, { desc = "Debug: preview widget" })
map("n", "<Leader>df", function()
	local widgets = require("dap.ui.widgets")
	widgets.centered_float(widgets.frames)
end, { desc = "Debug: show frames" })
map("n", "<Leader>ds", function()
	local widgets = require("dap.ui.widgets")
	widgets.centered_float(widgets.scopes)
end, { desc = "Debug: show scopes" })