set -g mouse on
setw -g mode-keys vi
set -sg escape-time 10
set-option -g default-terminal "tmux-256color"
set -ga terminal-overrides ',xterm-256color:Tc'
set -g set-clipboard on
set -g allow-passthrough on
set -g history-limit 10000
set -g focus-events on

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel

bind-key -r j select-pane -D
bind-key -r k select-pane -U
bind-key -r h select-pane -L
bind-key -r l select-pane -R

# Split horiziontal and vertical splits, instead of % and "
# Also open them in the same directory
bind-key v split-window -h -c '#{pane_current_path}'
bind-key s split-window -v -c '#{pane_current_path}'
