[general]
live_config_reload = true

[terminal]

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x666666"
blue = "0x7aa6da"
cyan = "0x54ced6"
green = "0x9ec400"
magenta = "0xb77ee0"
red = "0xff6d67"
white = "0xffffff"
yellow = "0xe7c547"

[colors.cursor]
cursor = "0xcccccc"
text = "0x111111"

[colors.dim]
black = "0x333333"
blue = "0x6699cc"
cyan = "0x66cccc"
green = "0x99cc99"
magenta = "0xcc99cc"
red = "0xf2777a"
white = "0xdddddd"
yellow = "0xffcc66"

[colors.normal]
black = "0x000000"
blue = "0x7aa6da"
cyan = "0x70c0ba"
green = "0xb9ca4a"
magenta = "0xc397d8"
red = "0xc91b00"
white = "0xffffff"
yellow = "0xe6c547"

[colors.primary]
background = "0x1e1e1e"
foreground = "0xc7c7c7"

[cursor]
style = "Block"
unfocused_hollow = false

[debug]
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.bold]
family = "JetBrainsMono NF"
style = "SemiBold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono NF"
style = "Regular Italic"

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

# [mouse.double_click]
# threshold = 300

# [mouse.hints]
# launcher = "open"

# [mouse.triple_click]
# threshold = 300

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ''',│`|:"' ()[]{}<>'''

[terminal.shell]
args = ["--login"]
program = "/usr/bin/fish"

[window]
decorations = "full"
dynamic_padding = false
decorations_theme_variant = "Dark"

[window.dimensions]
columns = 160
lines = 48

[window.padding]
x = 2
y = 2

[keyboard]

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Control|Shift"


[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Control|Shift"


[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
mods = "Control|Shift"
